// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_BDqpyXtCKZzzEaGYyOaHoHoGKUrj8c',
    appId: '1:827683228986:web:d2971321eaec362582d403',
    messagingSenderId: '827683228986',
    projectId: 'rove-assistant',
    authDomain: 'rove-assistant.firebaseapp.com',
    storageBucket: 'rove-assistant.firebasestorage.app',
    measurementId: 'G-9VML89BSQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx9BcYdXGj9fXk6YnWJRWFrVStHqUfCWY',
    appId: '1:827683228986:android:196552d6398e333d82d403',
    messagingSenderId: '827683228986',
    projectId: 'rove-assistant',
    storageBucket: 'rove-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ujGK6aMDaHoQQSdKS04isVhKBvQZH-k',
    appId: '1:827683228986:ios:d87a1ff295324ef082d403',
    messagingSenderId: '827683228986',
    projectId: 'rove-assistant',
    storageBucket: 'rove-assistant.firebasestorage.app',
    iosBundleId: 'com.example.roveAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ujGK6aMDaHoQQSdKS04isVhKBvQZH-k',
    appId: '1:827683228986:ios:d87a1ff295324ef082d403',
    messagingSenderId: '827683228986',
    projectId: 'rove-assistant',
    storageBucket: 'rove-assistant.firebasestorage.app',
    iosBundleId: 'com.example.roveAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7_BDqpyXtCKZzzEaGYyOaHoHoGKUrj8c',
    appId: '1:827683228986:web:dbb60459e92d0d6982d403',
    messagingSenderId: '827683228986',
    projectId: 'rove-assistant',
    authDomain: 'rove-assistant.firebaseapp.com',
    storageBucket: 'rove-assistant.firebasestorage.app',
    measurementId: 'G-MY2K3M5Z1M',
  );
}
