name: rove_data_types
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  function_tree: ^0.9.1
  uuid: ^4.0.0
  meta: ^1.15.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
